#!/bin/bash
#############################################
# Cipi — shell tab-completion
#
#   cipi completion bash [--print]
#   cipi completion zsh  [--print]
#
# --print   write the completion script to stdout and change nothing.
# default   install it and add an idempotent loader to the caller's rc file
#           so a running shell picks it up on its next start.
#
# setup.sh and `cipi self-update` regenerate the system files directly with
#   cipi completion bash --print > /etc/bash_completion.d/cipi
#   cipi completion zsh  --print > /usr/share/zsh/vendor-completions/_cipi
# so a fresh server already has completion before anyone runs the command.
#
# Three things have to hold for <Tab> to do something on a real server:
#   - the script is loaded in the shell at hand. Login shells get it from
#     /etc/profile.d; `sudo -s`, `su`, tmux and screen start non-login shells,
#     which only read ~/.bashrc, so root and the cipi user get a loader there.
#   - `sudo cipi …` completes, because that is how the cipi user runs it. With
#     the bash-completion package sudo's completion hands over to ours; without
#     it sudo has none, and _cipi_sudo_complete takes its place.
#   - app names complete for the cipi user too, who cannot read /etc/cipi: app
#     users are the members of the cipi-apps group, which anyone can list.
#
# The verb list is a hand-kept copy of the dispatch in `cipi` — nothing
# generates it. tests/verify-5.2.0.sh fails if the two drift.
#############################################

# Plain (not readonly): setup.sh and self-update.sh source this file too.
_CIPI_BASH_COMPLETION="/etc/bash_completion.d/cipi"
_CIPI_ZSH_COMPLETION="/usr/share/zsh/vendor-completions/_cipi"
_CIPI_PROFILE_D="/etc/profile.d/cipi-completion.sh"
_CIPI_COMPLETION_MARKER="# cipi completion"
# Interactive shells only: bash also reads ~/.bashrc for a command run over ssh.
_CIPI_BASHRC_LOADER="case \$- in *i*) [ -r $_CIPI_BASH_COMPLETION ] && . $_CIPI_BASH_COMPLETION ;; esac"

# ── the bash completion function ────────────────────────────
# Emitted verbatim. It must stand on its own: the interactive shell that
# sources it has almost certainly never run `cipi` (mode 700, root only), so it
# never shells out to cipi. App names come from the plaintext projection
# /etc/cipi/apps-public.json when the shell's user can read it (root, or the
# cipi-api group), and from the cipi-apps group otherwise.
_completion_bash_script() {
    cat <<'BASH_COMPLETION'
# cipi(1) bash completion — generated by `cipi completion bash`
_cipi_complete() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n = || return
    else
        COMPREPLY=(); cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}"); cword=$COMP_CWORD
    fi

    local commands="status disk version self-update service app node alias domains www redirect proxy auth basicauth deploy worker schedule health monitor db search ssl php package firewall ban crowdsec zt scan compliance backup ini yml nginx api gui git sync ssh smtp notifications reset completion help"
    local topics="app node domains www redirect proxy deploy worker schedule health monitor db search service ssl php package auth basicauth ssh firewall ban crowdsec zt scan compliance backup sync git ini yml nginx api gui smtp notifications reset server completion all"

    # skip a leading path/wrapper (e.g. `sudo cipi`, `/usr/local/bin/cipi`)
    local start=1 j
    for (( j = 0; j < cword; j++ )); do
        [[ "${words[j]##*/}" == cipi ]] && { start=$(( j + 1 )); break; }
    done

    # locate the verb: first non-option word after the cipi path
    local i verb="" vi=0
    for (( i = start; i < cword; i++ )); do
        case "${words[i]}" in
            -*|sudo|command|env) ;;
            *) verb="${words[i]}"; vi=$i; break ;;
        esac
    done

    if [[ -z "$verb" ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") ); return
    fi

    local pos=$(( cword - vi ))      # 1 = first arg after the verb
    local w1="${words[vi+1]:-}"      # first arg after the verb
    local w2="${words[vi+2]:-}"      # second arg after the verb

    _cipi_apps() {
        local f=/etc/cipi/apps-public.json
        if [[ ! -r $f ]]; then
            # The cipi user behind sudo cannot read /etc/cipi. App users are
            # the members of cipi-apps, and group membership is public.
            getent group cipi-apps 2>/dev/null | cut -d: -f4 | tr ',' '\n'
            return 0
        fi
        if command -v jq >/dev/null 2>&1; then
            jq -r 'keys[]' "$f" 2>/dev/null
        else
            # fallback: jq writes apps-public.json with 2-space indent, so the
            # top-level app keys are the ones at exactly two spaces.
            sed -n 's/^  "\([A-Za-z0-9_.-]\{1,\}\)": .*/\1/p' "$f" 2>/dev/null
        fi
    }

    local sub=""
    case "$verb" in
        help)        COMPREPLY=( $(compgen -W "$topics" -- "$cur") ); return ;;
        completion)  COMPREPLY=( $(compgen -W "bash zsh --print" -- "$cur") ); return ;;
        self-update) sub="--check" ;;
        disk)        sub="db --json" ;;

        service)
            case $pos in
                1) sub="list restart start stop upgrade" ;;
                2) case "$w1" in
                       upgrade) sub="nginx mariadb postgresql valkey --yes" ;;
                       *)       sub="nginx mariadb postgresql valkey-server supervisor fail2ban meilisearch crowdsec cloudflared php all" ;;
                   esac ;;
            esac ;;

        app)
            case $pos in
                1) sub="create list show edit convert clone reverb limits delete suspend unsuspend env logs tinker artisan run deploy-config reset-password reset-db-password fix-permissions" ;;
                2) case "$w1" in
                       create) sub="--custom --octane --engine= --node= --framework= --node-version= --build= --start= --output= --health-path=" ;;
                       reverb) sub="enable disable status" ;;
                       run)    sub="--commands" ;;
                       list)   ;;
                       *)      sub="$(_cipi_apps)" ;;
                   esac ;;
                3) case "$w1" in
                       convert) sub="--to=octane --to=fpm" ;;
                       reverb)  sub="$(_cipi_apps)" ;;
                       limits)  sub="--fpm-max-children= --memory-limit= --octane-workers= --worker-procs= --disk=" ;;
                   esac ;;
            esac ;;

        alias)
            case $pos in
                1) sub="add remove list" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        www)
            case $pos in
                1) sub="add force-to-root force-from-root clear status" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        redirect|redirects)
            case $pos in
                1) sub="set enable disable unset add remove list" ;;
                2) sub="$(_cipi_apps)" ;;
                *) case "$w1" in
                       set)      sub="--to= --301 --302 --307 --308 --no-path" ;;
                       add)      sub="--301 --302 --307 --308 --no-path" ;;
                       list)     sub="--json" ;;
                   esac ;;
            esac ;;

        proxy)
            case $pos in
                1) sub="add remove list" ;;
                2) sub="$(_cipi_apps)" ;;
                *) case "$w1" in
                       add)  sub="--strip-prefix --preserve-host --timeout= --no-buffering --force" ;;
                       list) sub="--json" ;;
                   esac ;;
            esac ;;

        auth)
            case $pos in
                1) sub="create edit show delete" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        basicauth)
            case $pos in
                1) sub="enable disable status" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        deploy)
            if [[ $pos -eq 1 ]]; then sub="$(_cipi_apps)"
            else sub="--snapshot --rollback --releases --log --key --webhook --unlock --trust-host= --rollback-on-unhealthy --audit --days= --json"; fi ;;

        worker)
            case $pos in
                1) sub="add list remove restart horizon" ;;
                2) case "$w1" in horizon) sub="enable disable status" ;; *) sub="$(_cipi_apps)" ;; esac ;;
                3) case "$w1" in horizon) sub="$(_cipi_apps)" ;; esac ;;
            esac ;;

        schedule)
            case $pos in
                1) sub="status on off" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        health)
            case $pos in
                1) sub="set unset check postdeploy list" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        db)
            case $pos in
                1) sub="engines install uninstall default create list delete backup restore password upgrade" ;;
                2) case "$w1" in
                       install|uninstall|default|upgrade) sub="mariadb pgsql" ;;
                   esac ;;
                3) case "$w1" in upgrade) sub="--yes" ;; esac ;;
            esac ;;

        node)
            case $pos in
                1) sub="install default list upgrade remove status restart logs" ;;
                2) case "$w1" in
                       install|upgrade|remove) sub="22 24" ;;
                       default)                sub="22 24 system" ;;
                       status|restart|logs)    sub="$(_cipi_apps)" ;;
                   esac ;;
            esac ;;

        search)
            case $pos in
                1) sub="install status enable disable list key upgrade remove" ;;
                2) case "$w1" in
                       enable)  sub="$(_cipi_apps)" ;;
                       disable) sub="$(_cipi_apps) --purge-indexes" ;;
                       key)     sub="rotate show" ;;
                       install) sub="--version= --port= --force" ;;
                       upgrade) sub="--version= --reset-data --yes" ;;
                       remove)  sub="--keep-data --force" ;;
                       status)  sub="--check --json" ;;
                       list)    sub="--json" ;;
                   esac ;;
                3) case "$w1" in
                       key)     sub="$(_cipi_apps) --master" ;;
                       disable) sub="--purge-indexes" ;;
                   esac ;;
            esac ;;

        ssl)
            case $pos in
                1) sub="install dns force renew status" ;;
                2) case "$w1" in
                       install|force) sub="$(_cipi_apps)" ;;
                       dns)           sub="set list remove" ;;
                   esac ;;
                *) case "$w1" in
                       install) sub="--dns=cloudflare --account= --wildcard --no-wildcard --http" ;;
                       dns)     case "$w2" in set) sub="--name= --token=" ;; esac ;;
                   esac ;;
            esac ;;

        php)      [[ $pos -eq 1 ]] && sub="list install switch upgrade" ;;

        package|packages)
            case $pos in
                1) sub="list install remove" ;;
                2) case "$w1" in
                       install|remove) sub="image-optimizers ffmpeg imagemagick poppler-utils jpegoptim optipng pngquant gifsicle webp" ;;
                       list)           sub="--json" ;;
                   esac ;;
                3) case "$w1" in
                       install) sub="--yes --force" ;;
                       remove)  sub="--yes --autoremove" ;;
                   esac ;;
            esac ;;

        firewall) [[ $pos -eq 1 ]] && sub="allow list attempts" ;;
        ban)      [[ $pos -eq 1 ]] && sub="list unban" ;;

        crowdsec)
            case $pos in
                1) sub="enable disable status allow unallow rescue" ;;
                2) case "$w1" in rescue) sub="token rotate" ;; esac ;;
            esac ;;

        zt|zerotrust)
            case $pos in
                1) sub="token enable disable status refresh hostname access ssh lock unlock origin-cert" ;;
                2) case "$w1" in
                       token)    sub="set show" ;;
                       hostname) sub="add remove list" ;;
                       access)   sub="enable disable" ;;
                       ssh)      sub="enable disable unlock" ;;
                       lock)     sub="http ssh" ;;
                       unlock)   sub="http ssh" ;;
                   esac ;;
            esac ;;

        compliance)
            case $pos in
                1) sub="check report list controls --days= --json" ;;
                *) case "$w1" in
                       report)      sub="--days= --out= --no-archive --json" ;;
                       check)       sub="--days= --json" ;;
                       list|controls) sub="--json" ;;
                   esac ;;
            esac ;;

        scan)
            [[ $pos -eq 1 ]] && sub="enable disable status manifest report $(_cipi_apps)" ;;

        backup)
            case $pos in
                1) sub="configure status profile run list verify prune fetch key" ;;
                2) case "$w1" in
                       profile) sub="list show add edit remove enable disable" ;;
                       key)     sub="show rotate" ;;
                   esac ;;
            esac ;;

        ini) [[ $pos -eq 1 ]] && sub="list get set unset reset keys" ;;

        yml|yaml)
            case $pos in
                1) sub="generate example validate plan apply auto post-deploy" ;;
                2) sub="$(_cipi_apps)" ;;
                3) case "$w1" in
                       auto) sub="on off status" ;;
                       generate|dump) sub="--save --force" ;;
                   esac ;;
            esac ;;

        nginx)
            case $pos in
                1) sub="default-server upgrade" ;;
                2) case "$w1" in
                       default-server) sub="status on off" ;;
                       upgrade)        sub="--yes" ;;
                   esac ;;
            esac ;;

        api)
            case $pos in
                1) sub="ssl update upgrade status token ip-whitelist fix-permissions" ;;
                2) case "$w1" in
                       token)        sub="list create revoke" ;;
                       ip-whitelist) sub="show add remove set allow-all" ;;
                   esac ;;
            esac ;;

        gui|panel) [[ $pos -eq 1 ]] && sub="ssl update refresh-theme upgrade status fix-permissions repair reset-user remove" ;;
        git)
            case $pos in
                1) sub="status github-token gitlab-token gitlab-url origin-token bitbucket-token azure-token codecommit-token remove-github remove-gitlab remove-origin remove-bitbucket remove-azure remove-codecommit refresh" ;;
                2) case "$w1" in
                       refresh) sub="$(_cipi_apps) --rotate-keys --rotate-secret --force" ;;
                   esac ;;
                3) case "$w1" in
                       refresh) sub="--rotate-keys --rotate-secret --force" ;;
                   esac ;;
            esac ;;
        sync)      [[ $pos -eq 1 ]] && sub="export import push list pubkey trust" ;;
        ssh)
            case $pos in
                1) sub="list add remove rename apps" ;;
                2) case "$w1" in apps) sub="enable disable --json" ;; esac ;;
                3) case "$w1" in apps) sub="$(_cipi_apps) --all" ;; esac ;;
            esac ;;

        smtp|mail|email)          [[ $pos -eq 1 ]] && sub="configure status test disable enable delete" ;;
        notifications|notify|triggers)
            case $pos in
                1) sub="list enable disable enable-all disable-all reset channel" ;;
                2) case "$w1" in
                       channel) sub="add list remove test enable disable" ;;
                   esac ;;
                3) case "$w2" in
                       add) sub="slack discord ntfy telegram webhook" ;;
                       remove|test|enable|disable) sub="" ;;
                   esac ;;
            esac ;;
        monitor)
            case $pos in
                1) sub="run list enable disable set test --json" ;;
                2) case "$w1" in
                       enable|disable) sub="disk app_disk ssl services workers http_5xx fs load" ;;
                       set)            sub="disk app_disk ssl http_5xx load reminder" ;;
                   esac ;;
                3) case "$w2" in
                       disk)     sub="--warn= --crit=" ;;
                       app_disk) sub="--warn= --minutes=" ;;
                       ssl)      sub="--days=" ;;
                       http_5xx) sub="--count= --ratio=" ;;
                       load)     sub="--factor= --runs=" ;;
                       reminder) sub="--minutes=" ;;
                   esac ;;
            esac ;;
        reset|passwords)          [[ $pos -eq 1 ]] && sub="root-password db-password valkey-password" ;;
    esac

    [[ -n "$sub" ]] && COMPREPLY=( $(compgen -W "$sub" -- "$cur") )
    return 0
}
complete -F _cipi_complete cipi

# `sudo cipi …` without the bash-completion package: sudo then has no completion
# of its own and <Tab> would only offer file names.
_cipi_sudo_complete() {
    # bash-completion was loaded after this file: its sudo completion is better.
    if declare -F _comp_command_offset >/dev/null 2>&1; then _comp_command_offset 1; return; fi
    if declare -F _command_offset >/dev/null 2>&1; then _command_offset 1; return; fi

    COMPREPLY=()
    local i
    for (( i = 1; i < COMP_CWORD; i++ )); do
        case "${COMP_WORDS[i]}" in
            -u|-g|-h|-p|-C|-D|-R|-T|-U|-r|-t) i=$(( i + 1 )) ;;   # option with a value
            -*) ;;
            *)  break ;;
        esac
    done
    if (( i >= COMP_CWORD )); then
        # still on the command word. cipi is named outright: it is mode 700,
        # so for the cipi user it is not among the commands compgen -c finds.
        COMPREPLY=( $(compgen -W "cipi" -- "${COMP_WORDS[COMP_CWORD]}") $(compgen -c -- "${COMP_WORDS[COMP_CWORD]}") )
    elif [[ "${COMP_WORDS[i]##*/}" == cipi ]]; then
        _cipi_complete
    fi
    return 0    # anything else: -o default completes file names
}
if [[ -n "${BASH_VERSION-}" && -z "${BASH_COMPLETION_VERSINFO-}" ]] && ! complete -p sudo >/dev/null 2>&1; then
    complete -o default -o bashdefault -F _cipi_sudo_complete sudo
fi
BASH_COMPLETION
}

# ── the zsh completion script ──────────────────────────────
# zsh reuses the bash function through bashcompinit. Installed to
# vendor-completions it may need one fresh prompt to bind; the ~/.zshrc loader
# added by `_completion_install` binds it before the first <Tab>.
_completion_zsh_script() {
    cat <<'ZSH_COMPLETION'
#compdef cipi
# cipi(1) zsh completion — generated by `cipi completion zsh`
if (( ! ${+functions[bashcompinit]} )); then
    autoload -Uz bashcompinit && bashcompinit
fi
ZSH_COMPLETION
    _completion_bash_script
}

# ── install ────────────────────────────────────────────────
# Write every system-wide file. Dependency-free and fail-safe on purpose:
# setup.sh and `cipi self-update` source this file and call this directly, and
# neither has common.sh (info/warn/...) loaded. Nothing here needs a manual
# step afterwards — a new login shell picks it up.
_completion_install_system() {
    _completion_bash_script > "$_CIPI_BASH_COMPLETION" 2>/dev/null || return 0
    chmod 644 "$_CIPI_BASH_COMPLETION" 2>/dev/null || true

    if [[ -d "$(dirname "$_CIPI_ZSH_COMPLETION")" ]]; then
        _completion_zsh_script > "$_CIPI_ZSH_COMPLETION" 2>/dev/null || true
        chmod 644 "$_CIPI_ZSH_COMPLETION" 2>/dev/null || true
    fi

    # Sourced by every interactive login shell (bash and zsh), with or without
    # the bash-completion package — so no dotfile edit is ever required.
    cat > "$_CIPI_PROFILE_D" 2>/dev/null <<'PROFILE' || return 0
# Cipi CLI tab-completion. Installed by Cipi; safe to delete.
if [ -n "${BASH_VERSION:-}" ]; then
    case $- in
        *i*) [ -r /etc/bash_completion.d/cipi ] && . /etc/bash_completion.d/cipi ;;
    esac
elif [ -n "${ZSH_VERSION:-}" ]; then
    if [ -r /etc/bash_completion.d/cipi ]; then
        autoload -Uz +X bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
        . /etc/bash_completion.d/cipi
    fi
fi
PROFILE
    chmod 644 "$_CIPI_PROFILE_D" 2>/dev/null || true

    # /etc/profile.d is for login shells only. `sudo -s`, `su`, tmux and screen
    # start non-login shells, which read ~/.bashrc and nothing else: root and
    # the cipi user, the two who can run cipi, get the loader there.
    local u h
    for u in root cipi; do
        h=$(getent passwd "$u" 2>/dev/null | cut -d: -f6 || true)
        [[ -n "$h" && -d "$h" ]] || continue
        _completion_rc_loader "$h/.bashrc" "$u" "$_CIPI_BASHRC_LOADER" || true
    done
    return 0
}

# Appends the loader to an rc file once. 0: added, 1: already there, 2: could
# not write. Quiet: _completion_install_system runs without common.sh.
_completion_rc_loader() {
    local rc="$1" user="$2" line="$3"
    if [[ -f "$rc" ]] && grep -qF "$_CIPI_COMPLETION_MARKER" "$rc" 2>/dev/null; then
        return 1
    fi
    local existed=false
    [[ -e "$rc" || -L "$rc" ]] && existed=true
    { echo ""; echo "$_CIPI_COMPLETION_MARKER"; echo "$line"; } >> "$rc" 2>/dev/null || return 2
    # Only a file created just now changes hands, and never through a link.
    if [[ "$existed" == false && -n "$user" && "$user" != "root" ]]; then
        chown -h "$user" "$rc" 2>/dev/null || true
    fi
    return 0
}

_completion_add_loader() {
    local rc="$1" user="$2" line="$3" rcode=0
    _completion_rc_loader "$rc" "$user" "$line" || rcode=$?
    case "$rcode" in
        0) success "Added the cipi completion loader to ${rc}" ;;
        1) info "${rc} already loads cipi completion" ;;
        *) warn "Could not write ${rc}" ;;
    esac
}

_completion_install() {
    local shell="$1" rc user home

    if _completion_install_system; then
        success "Wrote ${_CIPI_BASH_COMPLETION}"
        [[ -f "$_CIPI_ZSH_COMPLETION" ]] && success "Wrote ${_CIPI_ZSH_COMPLETION}"
        [[ -f "$_CIPI_PROFILE_D" ]]      && success "Wrote ${_CIPI_PROFILE_D}"
    else
        warn "Could not write the system completion files"
    fi

    # whose rc file to touch — the invoking user, not root, under `sudo cipi`
    user="${SUDO_USER:-$(id -un)}"
    home=$(getent passwd "$user" 2>/dev/null | cut -d: -f6)
    [[ -z "$home" || ! -d "$home" ]] && home="$HOME"

    if [[ "$shell" == bash ]]; then
        rc="$home/.bashrc"
        _completion_add_loader "$rc" "$user" "$_CIPI_BASHRC_LOADER"
    else
        rc="$home/.zshrc"
        _completion_add_loader "$rc" "$user" "if [ -r $_CIPI_BASH_COMPLETION ]; then autoload -Uz +X bashcompinit && bashcompinit; . $_CIPI_BASH_COMPLETION; fi"
    fi

    echo ""
    info "Active in any new ${shell} shell. For this one:  source ${rc}"
}

_completion_help() {
    cat <<'EOF'

  cipi completion bash [--print]   Install bash tab-completion
  cipi completion zsh  [--print]   Install zsh tab-completion

  --print   Write the script to stdout and change nothing.

  Without --print it writes /etc/bash_completion.d/cipi (and, for zsh,
  /usr/share/zsh/vendor-completions/_cipi when that directory exists) and
  adds a loader to your ~/.bashrc or ~/.zshrc. Open a new shell afterwards.

  setup.sh and 'cipi self-update' already install it for login shells
  (/etc/profile.d) and, through ~/.bashrc, for root and the cipi user in
  every other shell (sudo -s, su, tmux). This command is for another user,
  a non-standard rc file, or regenerating the script.

  'sudo cipi <Tab>' completes with or without the bash-completion package.
  App names complete for every user.

EOF
}

completion_command() {
    local shell="" print=0 a
    for a in "$@"; do
        case "$a" in
            bash|zsh)       shell="$a" ;;
            --print)        print=1 ;;
            -h|--help|help) _completion_help; return 0 ;;
            *) error "Unknown argument: $a"; _completion_help; exit 1 ;;
        esac
    done

    [[ -z "$shell" ]] && shell="$(basename "${SHELL:-bash}")"
    [[ "$shell" != bash && "$shell" != zsh ]] && shell="bash"

    if [[ "$print" -eq 1 ]]; then
        [[ "$shell" == zsh ]] && _completion_zsh_script || _completion_bash_script
        return 0
    fi

    _completion_install "$shell"
}
