#!/bin/bash
#############################################
# Cipi — shell tab-completion
#
#   cipi completion bash [--print]
#   cipi completion zsh  [--print]
#
# --print   write the completion script to stdout and change nothing.
# default   install it and add an idempotent loader to the caller's rc file
#           so a running shell picks it up on its next start.
#
# setup.sh and `cipi self-update` regenerate the system files directly with
#   cipi completion bash --print > /etc/bash_completion.d/cipi
#   cipi completion zsh  --print > /usr/share/zsh/vendor-completions/_cipi
# so a fresh server already has completion before anyone runs the command.
#
# The verb list is a hand-kept copy of the dispatch in `cipi` — nothing
# generates it. tests/verify-5.2.0.sh fails if the two drift.
#############################################

# Plain (not readonly): setup.sh and self-update.sh source this file too.
_CIPI_BASH_COMPLETION="/etc/bash_completion.d/cipi"
_CIPI_ZSH_COMPLETION="/usr/share/zsh/vendor-completions/_cipi"
_CIPI_PROFILE_D="/etc/profile.d/cipi-completion.sh"
_CIPI_COMPLETION_MARKER="# cipi completion"

# ── the bash completion function ────────────────────────────
# Emitted verbatim. It must stand on its own: the interactive shell that
# sources it has almost certainly never run `cipi` (mode 700, root only), so it
# never shells out to cipi. Dynamic values come from the plaintext projection
# /etc/cipi/apps-public.json when the shell's user can read it (root, or the
# cipi-api group); otherwise only the static verbs are offered.
_completion_bash_script() {
    cat <<'BASH_COMPLETION'
# cipi(1) bash completion — generated by `cipi completion bash`
_cipi_complete() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n = || return
    else
        COMPREPLY=(); cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}"); cword=$COMP_CWORD
    fi

    local commands="status version self-update service app alias domains www auth basicauth deploy worker schedule health db search ssl php package firewall ban crowdsec scan backup ini yml nginx api gui git sync ssh smtp notifications reset completion help"
    local topics="app domains www deploy worker schedule health db search service ssl php package auth basicauth ssh firewall ban crowdsec scan backup sync git ini yml nginx api gui smtp notifications reset server completion all"

    # skip a leading path/wrapper (e.g. `sudo cipi`, `/usr/local/bin/cipi`)
    local start=1 j
    for (( j = 0; j < cword; j++ )); do
        [[ "${words[j]##*/}" == cipi ]] && { start=$(( j + 1 )); break; }
    done

    # locate the verb: first non-option word after the cipi path
    local i verb="" vi=0
    for (( i = start; i < cword; i++ )); do
        case "${words[i]}" in
            -*|sudo|command|env) ;;
            *) verb="${words[i]}"; vi=$i; break ;;
        esac
    done

    if [[ -z "$verb" ]]; then
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") ); return
    fi

    local pos=$(( cword - vi ))      # 1 = first arg after the verb
    local w1="${words[vi+1]:-}"      # first arg after the verb

    _cipi_apps() {
        local f=/etc/cipi/apps-public.json
        [[ -r $f ]] || return 0
        if command -v jq >/dev/null 2>&1; then
            jq -r 'keys[]' "$f" 2>/dev/null
        else
            # fallback: jq writes apps-public.json with 2-space indent, so the
            # top-level app keys are the ones at exactly two spaces.
            sed -n 's/^  "\([A-Za-z0-9_.-]\{1,\}\)": .*/\1/p' "$f" 2>/dev/null
        fi
    }

    local sub=""
    case "$verb" in
        help)        COMPREPLY=( $(compgen -W "$topics" -- "$cur") ); return ;;
        completion)  COMPREPLY=( $(compgen -W "bash zsh --print" -- "$cur") ); return ;;
        self-update) sub="--check" ;;

        service)
            case $pos in
                1) sub="list restart start stop" ;;
                2) sub="nginx mariadb postgresql valkey-server supervisor fail2ban meilisearch crowdsec php all" ;;
            esac ;;

        app)
            case $pos in
                1) sub="create list show edit convert clone reverb limits delete suspend unsuspend env logs tinker artisan run deploy-config reset-password reset-db-password fix-permissions" ;;
                2) case "$w1" in
                       create) sub="--custom --octane --engine=" ;;
                       reverb) sub="enable disable status" ;;
                       run)    sub="--commands" ;;
                       list)   ;;
                       *)      sub="$(_cipi_apps)" ;;
                   esac ;;
                3) case "$w1" in
                       convert) sub="--to=octane --to=fpm" ;;
                       reverb)  sub="$(_cipi_apps)" ;;
                   esac ;;
            esac ;;

        alias)
            case $pos in
                1) sub="add remove list" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        www)
            case $pos in
                1) sub="add force-to-root force-from-root clear status" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        auth)
            case $pos in
                1) sub="create edit show delete" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        basicauth)
            case $pos in
                1) sub="enable disable status" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        deploy)
            if [[ $pos -eq 1 ]]; then sub="$(_cipi_apps)"
            else sub="--snapshot --rollback --releases --log --key --webhook --unlock --trust-host= --rollback-on-unhealthy"; fi ;;

        worker)
            case $pos in
                1) sub="add list remove restart horizon" ;;
                2) case "$w1" in horizon) sub="enable disable status" ;; *) sub="$(_cipi_apps)" ;; esac ;;
                3) case "$w1" in horizon) sub="$(_cipi_apps)" ;; esac ;;
            esac ;;

        schedule)
            case $pos in
                1) sub="status on off" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        health)
            case $pos in
                1) sub="set unset check postdeploy list" ;;
                2) sub="$(_cipi_apps)" ;;
            esac ;;

        db)
            case $pos in
                1) sub="engines install uninstall default create list delete backup restore password" ;;
                2) case "$w1" in install|uninstall|default) sub="mariadb pgsql" ;; esac ;;
            esac ;;

        search)
            case $pos in
                1) sub="install status enable disable list key upgrade remove" ;;
                2) case "$w1" in
                       enable)  sub="$(_cipi_apps)" ;;
                       disable) sub="$(_cipi_apps) --purge-indexes" ;;
                       key)     sub="rotate show" ;;
                       install) sub="--version= --port= --force" ;;
                       upgrade) sub="--version= --reset-data --yes" ;;
                       remove)  sub="--keep-data --force" ;;
                       status)  sub="--check --json" ;;
                       list)    sub="--json" ;;
                   esac ;;
                3) case "$w1" in
                       key)     sub="$(_cipi_apps) --master" ;;
                       disable) sub="--purge-indexes" ;;
                   esac ;;
            esac ;;

        ssl)
            case $pos in
                1) sub="install dns force renew status" ;;
                2) case "$w1" in
                       install|force) sub="$(_cipi_apps)" ;;
                       dns)           sub="set" ;;
                   esac ;;
            esac ;;

        php)      [[ $pos -eq 1 ]] && sub="list install switch upgrade" ;;

        package|packages)
            case $pos in
                1) sub="list install remove" ;;
                2) case "$w1" in
                       install|remove) sub="image-optimizers ffmpeg imagemagick poppler-utils jpegoptim optipng pngquant gifsicle webp" ;;
                       list)           sub="--json" ;;
                   esac ;;
                3) case "$w1" in
                       install) sub="--yes --force" ;;
                       remove)  sub="--yes --autoremove" ;;
                   esac ;;
            esac ;;

        firewall) [[ $pos -eq 1 ]] && sub="allow list" ;;
        ban)      [[ $pos -eq 1 ]] && sub="list unban" ;;

        crowdsec)
            case $pos in
                1) sub="enable disable status allow unallow rescue" ;;
                2) case "$w1" in rescue) sub="token rotate" ;; esac ;;
            esac ;;

        scan)
            [[ $pos -eq 1 ]] && sub="enable disable status manifest report $(_cipi_apps)" ;;

        backup)
            case $pos in
                1) sub="configure status profile run list verify prune fetch key" ;;
                2) case "$w1" in
                       profile) sub="list show add edit remove enable disable" ;;
                       key)     sub="show rotate" ;;
                   esac ;;
            esac ;;

        ini) [[ $pos -eq 1 ]] && sub="list get set unset reset keys" ;;

        yml|yaml)
            case $pos in
                1) sub="generate example validate plan apply auto" ;;
                2) sub="$(_cipi_apps)" ;;
                3) case "$w1" in auto) sub="on off status" ;; esac ;;
            esac ;;

        nginx)
            case $pos in
                1) sub="default-server" ;;
                2) case "$w1" in default-server) sub="status on off" ;; esac ;;
            esac ;;

        api)
            case $pos in
                1) sub="ssl update upgrade status token ip-whitelist fix-permissions" ;;
                2) case "$w1" in
                       token)        sub="list create revoke" ;;
                       ip-whitelist) sub="show add remove set allow-all" ;;
                   esac ;;
            esac ;;

        gui|panel) [[ $pos -eq 1 ]] && sub="ssl update refresh-theme upgrade status fix-permissions repair reset-user remove" ;;
        git)
            case $pos in
                1) sub="status github-token gitlab-token gitlab-url remove-github remove-gitlab refresh" ;;
                2) case "$w1" in
                       refresh) sub="$(_cipi_apps) --rotate-keys --rotate-secret --force" ;;
                   esac ;;
                3) case "$w1" in
                       refresh) sub="--rotate-keys --rotate-secret --force" ;;
                   esac ;;
            esac ;;
        sync)      [[ $pos -eq 1 ]] && sub="export import push list pubkey trust" ;;
        ssh)       [[ $pos -eq 1 ]] && sub="list add remove" ;;

        smtp|mail|email)          [[ $pos -eq 1 ]] && sub="configure status test disable enable delete" ;;
        notifications|notify|triggers) [[ $pos -eq 1 ]] && sub="list enable disable enable-all disable-all reset" ;;
        reset|passwords)          [[ $pos -eq 1 ]] && sub="root-password db-password valkey-password" ;;
    esac

    [[ -n "$sub" ]] && COMPREPLY=( $(compgen -W "$sub" -- "$cur") )
    return 0
}
complete -F _cipi_complete cipi
BASH_COMPLETION
}

# ── the zsh completion script ──────────────────────────────
# zsh reuses the bash function through bashcompinit. Installed to
# vendor-completions it may need one fresh prompt to bind; the ~/.zshrc loader
# added by `_completion_install` binds it before the first <Tab>.
_completion_zsh_script() {
    cat <<'ZSH_COMPLETION'
#compdef cipi
# cipi(1) zsh completion — generated by `cipi completion zsh`
if (( ! ${+functions[bashcompinit]} )); then
    autoload -Uz bashcompinit && bashcompinit
fi
ZSH_COMPLETION
    _completion_bash_script
}

# ── install ────────────────────────────────────────────────
# Write every system-wide file. Dependency-free and fail-safe on purpose:
# setup.sh and `cipi self-update` source this file and call this directly, and
# neither has common.sh (info/warn/...) loaded. Nothing here needs a manual
# step afterwards — a new login shell picks it up.
_completion_install_system() {
    _completion_bash_script > "$_CIPI_BASH_COMPLETION" 2>/dev/null || return 0
    chmod 644 "$_CIPI_BASH_COMPLETION" 2>/dev/null || true

    if [[ -d "$(dirname "$_CIPI_ZSH_COMPLETION")" ]]; then
        _completion_zsh_script > "$_CIPI_ZSH_COMPLETION" 2>/dev/null || true
        chmod 644 "$_CIPI_ZSH_COMPLETION" 2>/dev/null || true
    fi

    # Sourced by every interactive login shell (bash and zsh), with or without
    # the bash-completion package — so no dotfile edit is ever required.
    cat > "$_CIPI_PROFILE_D" 2>/dev/null <<'PROFILE' || return 0
# Cipi CLI tab-completion. Installed by Cipi; safe to delete.
if [ -n "${BASH_VERSION:-}" ]; then
    case $- in
        *i*) [ -r /etc/bash_completion.d/cipi ] && . /etc/bash_completion.d/cipi ;;
    esac
elif [ -n "${ZSH_VERSION:-}" ]; then
    if [ -r /etc/bash_completion.d/cipi ]; then
        autoload -Uz +X bashcompinit 2>/dev/null && bashcompinit 2>/dev/null
        . /etc/bash_completion.d/cipi
    fi
fi
PROFILE
    chmod 644 "$_CIPI_PROFILE_D" 2>/dev/null || true
    return 0
}

_completion_add_loader() {
    local rc="$1" user="$2" line="$3"
    if [[ -f "$rc" ]] && grep -qF "$_CIPI_COMPLETION_MARKER" "$rc"; then
        info "${rc} already loads cipi completion"
        return 0
    fi
    { echo ""; echo "$_CIPI_COMPLETION_MARKER"; echo "$line"; } >> "$rc" 2>/dev/null || {
        warn "Could not write ${rc}"
        return 0
    }
    [[ -n "$user" && "$user" != "root" ]] && chown "$user" "$rc" 2>/dev/null || true
    success "Added the cipi completion loader to ${rc}"
}

_completion_install() {
    local shell="$1" rc user home

    if _completion_install_system; then
        success "Wrote ${_CIPI_BASH_COMPLETION}"
        [[ -f "$_CIPI_ZSH_COMPLETION" ]] && success "Wrote ${_CIPI_ZSH_COMPLETION}"
        [[ -f "$_CIPI_PROFILE_D" ]]      && success "Wrote ${_CIPI_PROFILE_D}"
    else
        warn "Could not write the system completion files"
    fi

    # whose rc file to touch — the invoking user, not root, under `sudo cipi`
    user="${SUDO_USER:-$(id -un)}"
    home=$(getent passwd "$user" 2>/dev/null | cut -d: -f6)
    [[ -z "$home" || ! -d "$home" ]] && home="$HOME"

    if [[ "$shell" == bash ]]; then
        rc="$home/.bashrc"
        _completion_add_loader "$rc" "$user" "[ -r $_CIPI_BASH_COMPLETION ] && . $_CIPI_BASH_COMPLETION"
    else
        rc="$home/.zshrc"
        _completion_add_loader "$rc" "$user" "if [ -r $_CIPI_BASH_COMPLETION ]; then autoload -Uz +X bashcompinit && bashcompinit; . $_CIPI_BASH_COMPLETION; fi"
    fi

    echo ""
    info "Active in any new ${shell} shell. For this one:  source ${rc}"
}

_completion_help() {
    cat <<'EOF'

  cipi completion bash [--print]   Install bash tab-completion
  cipi completion zsh  [--print]   Install zsh tab-completion

  --print   Write the script to stdout and change nothing.

  Without --print it writes /etc/bash_completion.d/cipi (and, for zsh,
  /usr/share/zsh/vendor-completions/_cipi when that directory exists) and
  adds a loader to your ~/.bashrc or ~/.zshrc. Open a new shell afterwards.

  setup.sh and 'cipi self-update' already install it — this command is for
  a second shell, a non-standard rc file, or regenerating the script.

  App, database and service names complete only when your shell user can
  read /etc/cipi/apps-public.json (root, or a member of the cipi-api group).

EOF
}

completion_command() {
    local shell="" print=0 a
    for a in "$@"; do
        case "$a" in
            bash|zsh)       shell="$a" ;;
            --print)        print=1 ;;
            -h|--help|help) _completion_help; return 0 ;;
            *) error "Unknown argument: $a"; _completion_help; exit 1 ;;
        esac
    done

    [[ -z "$shell" ]] && shell="$(basename "${SHELL:-bash}")"
    [[ "$shell" != bash && "$shell" != zsh ]] && shell="bash"

    if [[ "$print" -eq 1 ]]; then
        [[ "$shell" == zsh ]] && _completion_zsh_script || _completion_bash_script
        return 0
    fi

    _completion_install "$shell"
}
